00:55:50 01/02/12 pinolo.irc.azzurra INFO Reconnecting to tophost.azzurra.org:6667 (azzurra)                                  [0/188]
00:59:00 01/02/12 pinolo.irc.azzurra ERROR Failed connection to: tophost.azzurra.org:6667 (ETIMEDOUT Connection timed out)
00:59:00 01/02/12 pinolo.irc.azzurra WARNING I'll be quiet for 120 seconds before trying to connect again
01:01:03 01/02/12 pinolo.irc.azzurra INFO Connected to: tophost.azzurra.org:6667 (azzurra)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/gevent/greenlet.py", line 388, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/sand/pinolo_git/pinolo/irc.py", line 244, in connect
    self.event_loop()
  File "/home/sand/pinolo_git/pinolo/irc.py", line 354, in event_loop
    self.connect()
  File "/home/sand/pinolo_git/pinolo/irc.py", line 244, in connect
    self.event_loop()
  File "/home/sand/pinolo_git/pinolo/irc.py", line 354, in event_loop
    self.connect()
  File "/home/sand/pinolo_git/pinolo/irc.py", line 244, in connect
    self.event_loop()
  File "/home/sand/pinolo_git/pinolo/irc.py", line 280, in event_loop
    line = self.stream.readline()
  File "/usr/lib/python2.6/socket.py", line 444, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/pymodules/python2.6/gevent/socket.py", line 327, in recv
    return self._sock.recv(*args)
error: [Errno 104] Connection reset by peer
<Greenlet at 0x256c738: <bound method IRCClient.connect of IRCClient(name: 'azzurra')>> failed with error

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/gevent/greenlet.py", line 388, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/sand/pinolo_git/pinolo/irc.py", line 401, in output_loop
    self.stream.flush()
  File "/usr/lib/python2.6/socket.py", line 297, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
  File "/usr/lib/pymodules/python2.6/gevent/socket.py", line 388, in sendall
    data_sent += self.send(data[data_sent:], flags)
  File "/usr/lib/pymodules/python2.6/gevent/socket.py", line 369, in send
    return self._sock.send(data, flags)
error: [Errno 32] Broken pipe
<Greenlet at 0x256c5a0: <bound method IRCClient.output_loop of IRCClient(name: 'azzurra')>> failed with error

